name: Deploy Vite React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Copy dist folder to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # ✅ Only copy the contents of dist, NOT the dist folder itself
          source: "dist/*"
          # ✅ Copy to the parent Chat_Application folder to avoid nested dist/dist
          target: "/home/ubuntu/ChatsApp/Chat_Application"

      - name: Fix permissions & reload NGINX on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chmod -R 755 /home/ubuntu/ChatsApp/Chat_Application/dist
            sudo chmod +x /home/ubuntu
            sudo chmod +x /home/ubuntu/ChatsApp
            sudo chmod +x /home/ubuntu/ChatsApp/Chat_Application
            sudo systemctl reload nginx
